server:
  port: 8084


spring:
  application:
    name: eureka-feign
  cloud:

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

#Feign是自带断路器的，在D版本的Spring Cloud之后，它没有默认打开。需要在配置文件中配置打开它
feign.hystrix.enabled: true