server:
  port: 8085


spring:
  application:
    name: eureka-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/


zuul:
  host:
          connect-timeout-millis: 3000
          socket-timeout-millis: 3000
  routes:
    api-a:
      path: /api-a/**
      serviceId: eureka-ribbon
    api-b:
      path: /api-b/**
      serviceId: eureka-feign


hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeout-in-milliseconds: 3000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

#com.netflix.zuul.exception.ZuulException: Forwarding error
#解决办法
#
#
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000
#
#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000
#
#zuul:
#  host:
#    connect-timeout-millis: 10000
#    socket-timeout-millis: 60000

